apiVersion: v1
kind: ServiceAccount
metadata:
  name: michal
---  
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: michal-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]   
  verbs: ["get", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: michal-role-binding
  namespace: default
subjects:
  - kind: "ServiceAccount"
    name: michal
roleRef:
  kind: Role
  name: michal-role
  apiGroup: rbac.authorization.k8s.io
